name: "Sencha App Builder"
description: "Build the frontend distribution for MAGIQ Frontend apps"
inputs:
  sencha-version:
    description: "Sencha SDK Version"
    required: true
  bucket-with-prefixes:
    description: "location where the artifacts will be pushed to"
    required: true
  sencha-sdk-bucket:
    description: "where the SDKS are located"
    required: true
  build-files:
    description: "required build files"
    required: true
  build-folder:
    description: "what folder do you want the output to be in"
    default: build
runs:
  using: 'node12'
  main: 'dist/index.js'
